# Generated by Django 4.1.3 on 2022-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=12)),
                ('desc', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
